[package]
name = "sqlx-helper"
version = "0.1.0"
authors = ["Robin Ole Heinemann <robin.ole.heinemann@t-online.de>"]
edition = "2018"

[dependencies]
quote = "*"
proc-macro2 = "*"
syn = { version = "*", features = ["full", "visit-mut"] }
darling = "*"

[lib]
proc-macro = true
